---
- name: check for supported operating system on target
  fail:
    msg: "the operating system of the target machine ({{ inventory_hostname }}) is not currently supported."
  when: ( ansible_distribution != "Ubuntu" and ansible_distribution_major_version not in [14, 16] )

- name: include distro specific tasks
  include_tasks: "{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}/{{ java_distribution }}-{{java_version}}.yml"
  when: (java_distribution is defined) and (java_version is defined)

- name: include distro specific tasks
  include_tasks: "default.yml"
  when: (java_distribution is not defined) or (java_version is not defined)
