---

- name: Make sure java-common is installed
  apt:
    update_cache: yes
    name: "{{ item }}"
  with_items:
    - java-common

- name: Download Amazon Corretto OpenJDK8 .deb file
  apt:
    deb: https://d3pxv6yz143wms.cloudfront.net/8.232.09.1/java-1.8.0-amazon-corretto-jdk_8.232.09-1_amd64.deb
    
- name: Make sure Amazon Corretto Java is selected
  alternatives:
    name: java
    path: "/usr/lib/jvm/java-1.8.0-amazon-corretto/jre/bin/java"